# Profile padrao
spring.profiles.active=h2

# Carrega credenciais locais (opcional, ignorado pelo git)
spring.config.import=optional:file:./secrets.properties

# Configuracoes
spring.application.name=pedido-service

# Configuracaes do SpringDoc OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
